name: ROS 2 Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up ROS 2
        uses: ros-tooling/setup-ros@v0.2.0
        with:
          distribution: humble  # 使用するROS 2ディストリビューションに合わせて変更

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the workspace
        run: |
          colcon build --symlink-install
          source install/setup.bash

      - name: Run tests
        run: |
          colcon test
          colcon test-result --verbose

