name: test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    container: ros:foxy

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install additional dependencies
        run: |
          apt-get update && apt-get install -y \
          python3-pip python3-colcon-common-extensions && \
          pip3 install speedtest-cli && \
          rm -rf /var/lib/apt/lists/*

      - name: Build and Test
        shell: bash
        run: |
          source /opt/ros/foxy/setup.bash
          colcon build
          source install/setup.bash
          timeout 30 ros2 run internet_speed_display internet_speed_node > /tmp/internet_speed.log || true
          grep 'Published:' /tmp/internet_speed.log || echo "Test failed: No published messages found."

